language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
before_install:
    - sudo apt-get install --reinstall  python2.7-dev
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests