language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
before_install:
    - wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tar.xz
    - tar xf Python-2.7.10.tar.xz
    - cd Python-2.7.10 ; ./configure && make altinstall
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests